services:
  app:
    image: node:20-alpine
    working_dir: /app/web
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 8000"
    environment:
      - NODE_ENV=development
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app/web
      - ./chains.yaml:/app/chains.yaml:ro
      - node_modules:/app/web/node_modules
volumes:
  node_modules:
