services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: preview
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    environment:
      - EMAIL=${EMAIL:-}
      - APP_HOST=${APP_HOST:-localhost}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
